Attempt to fix CI for CI error: void function seq-into
Error: void-function (seq-into)
  mapbacktrace(#f(compiled-function (evald func args flags) #<bytecode -0xc4fdb87c8512f81>))
  debug-early-backtrace()
  debug-early(error (void-function seq-into))
  seq-into("\32" vector)
  edmacro-parse-keys("C-z" nil)
  read-kbd-macro("C-z")
  (let ((old-key (read-kbd-macro (if (boundp 'evil-toggle-key) evil-toggle-key "C-z"))) (key (read-kbd-macro key))) (with-no-warnings (let ((--dolist-tail-- '((evil-motion-state-map evil-emacs-state) (evil-insert-state-map evil-emacs-state) (evil-emacs-state-map evil-exit-emacs-state)))) (while --dolist-tail-- (let ((pair (car --dolist-tail--))) (if (boundp (car pair)) (progn (let ((map (symbol-value (car pair))) (fun (car (cdr pair)))) (if (keymapp map) (progn (define-key map key fun) (define-key map old-key nil)))))) (setq --dolist-tail-- (cdr --dolist-tail--)))))))
  evil-set-toggle-key("C-z")
  (closure (dabbrev-case-distinction dabbrev-search-these-buffers-only t) (sym value) (evil-set-toggle-key value) (set-default sym value))(evil-toggle-key "C-z")
  custom-initialize-reset(evil-toggle-key (funcall #'(closure (dabbrev-case-distinction dabbrev-search-these-buffers-only t) nil "" "C-z")))
  custom-declare-variable(evil-toggle-key (funcall #'(closure (dabbrev-case-distinction dabbrev-search-these-buffers-only t) nil "" "C-z")) "The key used to change to and from Emacs state.\nMust be readable by `read-kbd-macro'. For example: \"C-z\"." :type string :group evil :set (closure (dabbrev-case-distinction dabbrev-search-these-buffers-only t) (sym value) (evil-set-toggle-key value) (set-default sym value)))
  eval-buffer(#<buffer  *load*-269510> nil "/Users/james/.emacs.d/straight/repos/evil-collection/.cask/29.0/elpa/evil-20220518.859/evil-vars.el" nil t)
  load-with-code-conversion("/Users/james/.emacs.d/straight/repos/evil-collection/.cask/29.0/elpa/evil-20220518.859/evil-vars.el" "/Users/james/.emacs.d/straight/repos/evil-collection/.cask/29.0/elpa/evil-20220518.859/evil-vars.el" nil t)
  require(evil-vars)
  byte-code("\302\303!\210\302\304!\210\302\305!\210\302\306!\210\302\307!\210\302\310!\210\302\311!\210\302\312!\210\302\313!\210\302\314!\210\302\315!\210\302\316!\210\302\317!\210\10\203<\0\302\320!\210\11\203D\0\302\321!\210\322\323!\210\324\325!\207" [evil-want-integration evil-want-keybinding require evil-vars evil-common evil-core evil-states evil-repeat evil-macros evil-search evil-ex evil-digraphs evil-types evil-commands evil-jumps evil-maps evil-integration evil-keybindings run-hooks evil-after-load-hook provide evil] 2)
  require(evil)
  eval-buffer(#<buffer  *load*-174914> nil "/Users/james/.emacs.d/straight/repos/evil-collection/evil-collection.el" nil t)
  load-with-code-conversion("/Users/james/.emacs.d/straight/repos/evil-collection/evil-collection.el" "/Users/james/.emacs.d/straight/repos/evil-collection/evil-collection.el" nil t)
  require(evil-collection)
  eval-buffer(#<buffer  *load*> nil "/Users/james/.emacs.d/straight/repos/evil-collection/test/evil-collection-magit-tests.el" nil t)
  load-with-code-conversion("/Users/james/.emacs.d/straight/repos/evil-collection/test/evil-collection-magit-tests.el" "/Users/james/.emacs.d/straight/repos/evil-collection/test/evil-collection-magit-tests.el" nil t)
  load("evil-collection-magit-tests.el" nil t)
  command-line-1(("-L" "." "-L" "./test" "-l" "evil-collection-magit-tests.el" "-f" "ert-run-tests-batch"))
  command-line()
  normal-top-level()
Symbol's function definition is void: seq-into